// This file would ideally be generated by the Supabase CLI:
// npx supabase gen types typescript --project-id aojnxzljnbvdvpjmtzbs --schema public > types/supabase.ts
// For now, here's a manual definition based on your 'projects' table.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string
          user_id: string
          website_name: string
          developer_name: string
          description: string
          created_at: string
          editor_content: Json | null // Array of EditorComponentModel
          published_content: Json | null // Array of EditorComponentModel
          last_published_at: string | null
        }
        Insert: {
          id?: string
          user_id: string 
          website_name: string
          developer_name: string
          description: string
          created_at?: string
          editor_content?: Json | null
          published_content?: Json | null
          last_published_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          website_name?: string
          developer_name?: string
          description?: string
          created_at?: string
          editor_content?: Json | null
          published_content?: Json | null
          last_published_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "projects_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users" // This refers to auth.users
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// You might also want to define a more specific type for your projects table rows
// if you need to use it frequently, though `Database['public']['Tables']['projects']['Row']` is standard.
export type ProjectRow = Database['public']['Tables']['projects']['Row'];
export type ProjectInsert = Database['public']['Tables']['projects']['Insert'];
export type ProjectUpdate = Database['public']['Tables']['projects']['Update'];